"""test_migrate

Revision ID: 29d6ee84ab7f
Revises: d22cd1832de5
Create Date: 2025-03-11 12:21:43.914668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d6ee84ab7f'
down_revision: Union[str, None] = 'd22cd1832de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('test_migrate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('News', 'test_migrate')
    # ### end Alembic commands ###
