"""Add index to url

Revision ID: 8859339694a1
Revises: 29d6ee84ab7f
Create Date: 2025-03-11 12:29:56.949855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8859339694a1'
down_revision: Union[str, None] = '29d6ee84ab7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_News_url'), 'News', ['url'], unique=False)
    op.drop_column('News', 'test_migrate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('test_migrate', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_News_url'), table_name='News')
    # ### end Alembic commands ###
